-- Captured from metadata.db in a stopped
-- crocodilestick/calibre-web-automated:v4.0.6 container on 2026-08-14.

CREATE TABLE authors (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE,
  sort TEXT COLLATE NOCASE,
  link TEXT NOT NULL DEFAULT '',
  UNIQUE(name)
);

CREATE TABLE books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL DEFAULT 'Unknown' COLLATE NOCASE,
  sort TEXT COLLATE NOCASE,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  pubdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  series_index REAL NOT NULL DEFAULT 1.0,
  author_sort TEXT COLLATE NOCASE,
  isbn TEXT DEFAULT '' COLLATE NOCASE,
  lccn TEXT DEFAULT '' COLLATE NOCASE,
  path TEXT NOT NULL DEFAULT '',
  flags INTEGER NOT NULL DEFAULT 1,
  uuid TEXT,
  has_cover BOOL DEFAULT 0,
  last_modified TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:00+00:00'
);

CREATE TABLE data (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  format TEXT NOT NULL COLLATE NOCASE,
  uncompressed_size INTEGER NOT NULL,
  name TEXT NOT NULL,
  UNIQUE(book, format)
);

CREATE TABLE books_authors_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  author INTEGER NOT NULL,
  UNIQUE(book, author)
);

CREATE TABLE publishers (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE,
  sort TEXT COLLATE NOCASE,
  UNIQUE(name)
);

CREATE TABLE books_publishers_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  publisher INTEGER NOT NULL,
  UNIQUE(book)
);

CREATE TABLE languages (
  id INTEGER PRIMARY KEY,
  lang_code TEXT NOT NULL COLLATE NOCASE,
  UNIQUE(lang_code)
);

CREATE TABLE books_languages_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  lang_code INTEGER NOT NULL,
  item_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE(book, lang_code)
);

CREATE TABLE series (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE,
  sort TEXT COLLATE NOCASE,
  UNIQUE(name)
);

CREATE TABLE books_series_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  series INTEGER NOT NULL,
  UNIQUE(book)
);

CREATE TABLE ratings (
  id INTEGER PRIMARY KEY,
  rating INTEGER CHECK(rating > -1 AND rating < 11),
  UNIQUE(rating)
);

CREATE TABLE books_ratings_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  UNIQUE(book, rating)
);

CREATE TABLE comments (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  text TEXT NOT NULL COLLATE NOCASE,
  UNIQUE(book)
);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE,
  UNIQUE(name)
);

CREATE TABLE books_tags_link (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  tag INTEGER NOT NULL,
  UNIQUE(book, tag)
);

CREATE TABLE identifiers (
  id INTEGER PRIMARY KEY,
  book INTEGER NOT NULL,
  type TEXT NOT NULL DEFAULT 'isbn' COLLATE NOCASE,
  val TEXT NOT NULL COLLATE NOCASE,
  UNIQUE(book, type)
);

CREATE TABLE book_format_checksums (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  book INTEGER NOT NULL,
  format TEXT NOT NULL COLLATE NOCASE,
  checksum TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT 'koreader',
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book) REFERENCES books(id) ON DELETE CASCADE
);
